.Dd $Mdocdate: December 29 2019 $
.Dt DIRNAME 1
.Os
.Sh NAME
.Nm dirname
.Nd return the directory portion of a pathname
.Sh SYNOPSIS
.Nm
.Ar string
.Sh DESCRIPTION
The
.Nm
utility strips the filename component, from
.Ar string ,
and writes the result to the standard output.
.Sh EXIT STATUS
.Ex -std
.Sh SEE ALSO
.Xr basename 1
.Sh STANDARDS
The
.Nm
utility is compliant with the
.St -p1003.1-2017
specification.
