.Dd $Mdocdate: December 29 2019 $
.Dt FALSE 1
.Os
.Sh NAME
.Nm false
.Nd return false value
.Sh SYNOPSIS
.Nm
.Sh DESCRIPTION
The
.Nm
utility always returns with non-zero exit code.
.Sh EXIT STATUS
The
.Nm
utility always returns with non-zero exit code.
.Sh SEE ALSO
.Xr true 1
.Sh STANDARDS
The
.Nm
utility is compliant with the
.St -p1003.1-2017
specification.
