.Dd $Mdocdate: March 14 2020 $
.Dt HOSTNAME 1
.Os
.Sh NAME
.Nm hostname
.Nd set or write the current host name
.Sh SYNOPSIS
.Nm
.Op Ar name
.Ar
.Sh DESCRIPTION
The
.Nm
utility sets the current host name to
.Ar name .
If no argument is given, the current host name is written
to the standard output.
.Sh EXIT STATUS
.Ex -std
