.Dd $Mdocdate: March 14 2020 $
.Dt ID 1
.Os
.Sh NAME
.Nm id
.Nd return user identity
.Sh SYNOPSIS
.Nm
.Oo
.Fl G | g | u
.Op Fl nr
.Oc
.Op Ar user
.Sh DESCRIPTION
The
.Nm
utility writes the user and group names and numeric IDs,
of the calling process, to the standard output.
If a
.Ar user
is specified, the user and group IDs of that user are
written to the standard output.
.Sh OPTIONS
.Bl -tag -width Ds
.It Fl G
Write the different group IDs.
.It Fl g
Write only the effective group ID.
.It Fl n
Write names instead of ID numbers.
.It Fl r
Write the real ID instead of the effective ID.
.It Fl u
Write only the effective user ID.
.El
.Sh EXIT STATUS
.Ex -std
.Sh SEE ALSO
.Xr who 1
.Sh STANDARDS
The
.Nm
utility is compliant with the
.St -p1003.1-2017
specification.
