.Dd $Mdocdate: December 29 2019 $
.Dt LINK 1
.Os
.Sh NAME
.Nm link
.Nd link files
.Sh SYNOPSIS
.Nm
.Ar source
.Ar target
.Sh DESCRIPTION
The
.Nm
utility creates a hard link
.Ar target
to
.Ar source .
.Sh EXIT STATUS
.Ex -std
.Sh SEE ALSO
.Xr ln 1
.Sh STANDARDS
The
.Nm
utility is compliant with the
.St -p1003.1-2017
specification.
