.Dd $Mdocdate: March 15 2020 $
.Dt MKFIFO 1
.Os
.Sh NAME
.Nm mkfifo
.Nd make FIFOs
.Sh SYNOPSIS
.Nm
.Op Fl m Ar mode
.Ar
.Sh DESCRIPTION
The
.Nm
utility creates a FIFO for each
.Ar file ,
in the order specified.
.Sh OPTIONS
.Bl -tag -width Ds
.It Fl m
Specify the mode.
.El
.Sh EXIT STATUS
.Ex -std
.Sh SEE ALSO
.Xr mknod 1
.Sh STANDARDS
The
.Nm
utility is compliant with the
.St -p1003.1-2017
specification.
