.Dd $Mdocdate: December 29 2019 $
.Dt PWD 1
.Os
.Sh NAME
.Nm pwd
.Nd return working directory name
.Sh SYNOPSIS
.Nm
.Op Fl L | P
.Sh DESCRIPTION
The
.Nm
utility writes an absolute pathname of the current working directory
to the standard output.
.Sh OPTIONS
.Bl -tag -width Ds
.It Fl L
Display the logical current working directory.
.It Fl P
Display the physical current working directory, with
all the symbolic links resolved.
.El
.Pp
The default is as if the
.Fl L
option had been specified.
.Sh ENVIRONMENT
.Bl -tag -width PWD
.It Ev PWD
The logical path to the current working directory.
.El
.Sh EXIT STATUS
.Ex -std
.Sh STANDARDS
The
.Nm
utility is compliant with the
.St -p1003.1-2017
specification.
