.Dd $Mdocdate: October 31 20 $
.Dt SLEEP 1
.Os
.Sh NAME
.Nm sleep
.Nd suspend execution for an interval
.Sh SYNOPSIS
.Nm
.Ar seconds
.Sh DESCRIPTION
The
.Nm
utility suspends execution for a minimum of the specified number of
.Ar seconds .
.Sh EXIT STATUS
.Ex -std
.Sh STANDARDS
The
.Nm
utility is compliant with the
.St -p1003.1-2017
specification.
