.Dd October 05, 2019
.Dt UNAME 1
.Os
.Sh NAME
.Nm uname
.Nd return system name
.Sh SYNOPSIS
.Nm
.Op Fl amnrsv
.Sh DESCRIPTION
The
.Nm
utility writes symbols representing one or more system characteristics
to the standard output.
.Sh OPTIONS
.Bl -tag -width Ds
.It Fl a
Behave as though all of the options
.Fl mnrsv
were specified.
.It Fl m
Print the machine hardware name.
.It Fl n
Print the nodename.
.It Fl r
Print the operating system release.
.It Fl s
Print the system name.
.It Fl v
Print the operating system version.
.El
.Pp
If no options are given, the default is as if the
.Fl s
option had been specified.
.Sh EXIT STATUS
.Ex -std
.Sh STANDARDS
The
.Nm
utility is compliant with the
.St -p1003.1-2008
specification.
