.Dd $Mdocdate: December 29 2019 $
.Dt UNLINK 1
.Os
.Sh NAME
.Nm unlink
.Nd unlink file
.Sh SYNOPSIS
.Nm
.Ar file
.Sh DESCRIPTION
The
.Nm
utility removes a link to a file.
.Sh EXIT STATUS
.Ex -std
.Sh SEE ALSO
.Xr rm 1 ,
.Xr rmdir 1 ,
.Xr unlink 2
.Sh STANDARDS
The
.Nm
utility is compliant with the
.St -p1003.1-2017
specification.
