.Dd October 03, 2019
.Dt YES 1
.Os
.Sh NAME
.Nm yes
.Nd generate an endless of the same word
.Sh SYNOPSIS
.Nm
.Op Ar string
.Sh DESCRIPTION
The
.Nm
utility writes repeatedly
.Ar string ,
followed by a line feed
.Pq Sq \en ,
to the standard output. If no
.Ar string
is given, the output will default to
.Sq y .
